spring.datasource.url=jdbc:mysql://localhost:3306/dent_crud?serverTimezone=Europe/Warsaw&useSSL=False&allowPublicKeyRetrieval=true
spring.datasource.username=dent_user
spring.datasource.password=1234321

spring.jpa.database=mysql
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update

info.company.name=DentClinic
info.company.address=Lalaland
info.company.email=nosuchemail@aero.com
info.company.phone=333333333

# EMAIL CONFIGURATION
spring.mail.host=smtp.mailtrap.io
spring.mail.port=2525
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true


